using System;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
public class SceneLoadManager : MonoBehaviour
{
    public static SceneLoadManager Instance;

    public GameObject LoadingScreen;
    public Image LoadingBack;
    public Image LoadingBar;
    public TMP_Text LoadingText;
    public TMP_Text LoadingDesc;


    private void Awake()
    {
        if (Instance == null)
        {
            Instance = this; //만들어진 자신을 인스턴스로 설정
        }
        else
        {
            Destroy(gameObject); //이미 인스턴스가 있으면 자신을 파괴
        }
    }

    private void Start()
    {
        SceneManager.sceneLoaded += OnSceneLoaded;
        OnSceneLoaded(SceneManager.GetActiveScene(), LoadSceneMode.Single);
    }

    private void Update()
    {

    }

    //씬이 로드되었을때 호출
    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {

        MonoBehaviour[] allObjs = UnityEngine.Object.FindObjectsByType<MonoBehaviour>(FindObjectsSortMode.None);

        foreach (var obj in allObjs)
        {
            if (obj is ISceneInitializable initializable)
            {
                //씬에서 ISceneInitializable 인터페이스를 가진 오브젝트의 초기화 로직을 실행
                initializable.OnSceneLoaded();
            }
        }
        
    }

    public void SetSceneLoadingProgressValue(float value)
    {
        LoadingBar.fillAmount = value;
        LoadingText.text = $"{(value * 100):F0}% 로딩중";
    }

    public void ShowLoadingScreen()
    {
        LoadingScreen.SetActive(true);
    }
    public void HideLoadingScreen()
    {
        LoadingScreen.SetActive(false);
    }

    public void RequestSceneChange(string sceneName)
    {
        _ = SceneChange(sceneName);
    }

    private async Awaitable SceneChange(string sceneName)
    {
        try
        {
            //로딩바 수치 0으로 설정
            SetSceneLoadingProgressValue(0f);

            ShowLoadingScreen();

            AsyncOperation op = SceneManager.LoadSceneAsync(sceneName);

            //자동 전환을 하고 싶지 않을 경우 해당값을 false로 두었다가 true로 바꾸면 그 때 전환됨
            op.allowSceneActivation = false;

            //화면에 보여줄 로딩 수치
            float displayProgress = 0f;

            //op.progress 0.9가 데이터 로딩이 끝난 기준 allowSceneActivation이 트루면 다음으로 넘어가면서 op.isDone이 true가 된다.
            while (op.progress < 0.9f) 
            {
                //실제 로딩 수치
                float realProgress = Mathf.Clamp01(op.progress / 0.9f);

                //보여줄 값을 실제값을 향해 부드럽게 이동
                displayProgress = Mathf.MoveTowards(displayProgress, realProgress, Time.deltaTime * 0.5f);

                // 로딩바 UI에 값 적용
                SetSceneLoadingProgressValue(displayProgress);

                //자기자신이 파괴될때 토큰에 취소요청을 보냄
                await Awaitable.NextFrameAsync(this.destroyCancellationToken);
            }

            //로딩바 수치 1(100%)로 설정 (데이터 로딩은 이미 끝이기 때문에)
            SetSceneLoadingProgressValue(1);

            // 잠시 대기했다가 전환
            await Awaitable.WaitForSecondsAsync(1.0f, this.destroyCancellationToken);

            // 다음씬으로 넘어가도 됨을 알림
            op.allowSceneActivation = true;

            // 씬 활성화가 완전히 끝날 때까지 대기
            // allowSceneActivation가 true가 되고 완전히 전환되기까지는 몇프레임 걸림. op.isDone 은 이 과정이 끝난 뒤에 true가 됨.
            while(!op.isDone)
            {
                await Awaitable.NextFrameAsync(this.destroyCancellationToken);
            }

            HideLoadingScreen();
        }
        catch (OperationCanceledException)
        {
            Debug.Log("씬 전환 작업이 취소됨");
        }
    }
}